start: run check early at start
This ensures that the configuration can be parsed before trying
to connect to redis. Do not use deploy checks here as external services
will not be available at this point.

diff --git a/start b/start
--- a/start
+++ b/start
@@ -130,6 +130,11 @@ if [ -n "$MEMCACHED_HOST" ] ; then
     >&2 echo "memcached is no longer supported, please configure redis"
 fi
 
+if ! run_weblate check ; then
+    >&2 echo "Failed to load configuration, please see errors above."
+    exit 1
+fi
+
 # Wait for redis
 TIMEOUT=0
 until run_weblate shell -c 'from django.core.cache import cache; cache.has_key("ping")' > /dev/null ; do
