start: Update required PostgreSQL version
Also include documentation link.

diff --git a/start b/start
--- a/start
+++ b/start
@@ -167,8 +167,9 @@ unset PGPASSWORD
 >&2 echo "Postgres $PGVERSION is up"
 
 # Check if supported PostgreSQL version is used
-if [ "$PGVERSION" -lt 100000 ] ; then
-    >&2 echo "PostgreSQL 10 or newer is required to run Weblate"
+if [ "$PGVERSION" -lt 120000 ] ; then
+    >&2 echo "PostgreSQL 12 or newer is required to run Weblate"
+    >&2 echo "See https://docs.weblate.org/en/latest/admin/install/docker.html#upgrading-postgresql-container"
     exit 1
 fi
 
